[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

# Configure Edge Functions
[[edge_functions]]
  function = "auth-middleware"
  path = ["/projects/*", "/projects"]

# Environment variables for local development
[context.dev.environment]
  JWT_SECRET = "auth-test-secret-key-netlify-dev"
  AUTH_PASSWORD = "1"

# Environment variables for production
[context.production.environment]
  JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
  AUTH_PASSWORD = "1"
